### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by LiorAgnin**

### CODE REVIEW

**Comment by thanhtrungzaz** [comment]
@LiorAgnin Hi thanks for adding me back my validator active and display on staking page but state are close . Could you open it help me .

**Comment by LiorAgnin** [comment]
@thanhtrungzaz I'll ask the team to open it for delegation.

**Comment by LiorAgnin** [comment]
@thanhtrungzaz Can you share your email & website (If you have one)?
You can send it to me privately to lior@fuse.io.

**Comment by thanhtrungzaz** [comment]
@LiorAgnin  I dont have website . my email : thanhtrungzaz@gmail.com . thanks your support

**Pull request merged**
